version: '3'

services:
  groupme-daily-games-ui:
    image: registry.docker.bland.work:443/daily-games-ui
    container_name: daily-games-ui
    restart: unless-stopped
    ports:
      - ${UI_PORT}:80
  groupme-daily-games-api:
    image: registry.docker.bland.work:443/daily-games-api
    container_name: daily-games-api
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP
      - PORT
      - HOSTNAME
      - DB_DIALECT
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - GROUPME_ACCESS_TOKEN
      - GROUPME_GROUP_NAME
